
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch('POSTGRES_HOST') { '127.0.0.1' } %>
  port: <%= ENV.fetch('POSTGRES_PORT') { 5432 } %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD') { '' } %>
  username: <%= ENV.fetch('POSTGRES_USERNAME') { '' } %>

development:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DATABASE') { 'contact_list_development' } %>

test:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DATABASE') { 'contact_list_test' } %>


production:
  <<: *default
  database: contact_list_production
  username: contact_list
  password: <%= ENV['CONTACT_LIST_DATABASE_PASSWORD'] %>
